module.exports = [
  "Faith needs no excuse",
  "In Terra's light we serve",
  "The seeds of heresy are planted in the minds of the enlightened",
  "Mankind stands upon the shoulders of the martyred",
  "Abhor the Night, it is the Light that Endures!",
  "The shield of faith is your best protection",
  "Honour thy oaths, honour thy Emperor",
  "Suffer not, the Heretic to live",
  "When the people forget their duty they are no longer human and become something less than beasts.",
  "Praise the Emperor",
  "Blessed be thy fury",
  "I speak with tongues of flame",
  "Smite all who oppose the Emperor",
  "Honour thy oaths, honour thy Emperor",
  "Carry your scars with honour",
  "The wise learn from the deaths of others",
  "Only in death does duty end",
  "Life is fleeting; duty is eternal",
  "Exist for the Emperor",
  "Let no foe stand before you",
  "Be the Emperor's reaper",
  "The righteous fear naught",
  "From duty and death there can be no respite",
  "Heed the Word of the Emperor",
  "The victor lives in honour; the vanquished dies in shame",
  "Life is the Emperor's currency, spend it well",
  "Aim without mercy",
  "Become vengeance",
  "Thou shalt kill",
  "Imperialis Dominatus",
  "In all things, serve the Emperor",
  "Death comes for us all",
  "Your honour is your life. Let none dispute it",
  "Without fear or falter, do thy duty",
  "Abhorrence is a gift; use it well",
  "The Emperor commands, the Astra Militarum obeys",
  "Foolish are those who fear nothing, yet claim to know everything",
  "Brave are they who know everything yet fear nothing"
]